/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CekKtaRouteImport } from './routes/cek-kta'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalBeritaRouteImport } from './routes/portal/berita'
import { Route as PortalEventRouteImport } from './routes/portal/event'
import { Route as PortalIdCardRouteImport } from './routes/portal/id-card'
import { Route as PortalProfilRouteImport } from './routes/portal/profil'
import { Route as PortalUbahPasswordRouteImport } from './routes/portal/ubah-password'
import { Route as DashboardActivityIndexRouteImport } from './routes/dashboard/activity/index'
import { Route as DashboardAttendanceIndexRouteImport } from './routes/dashboard/attendance/index'
import { Route as DashboardAuditTimelineIndexRouteImport } from './routes/dashboard/audit-timeline/index'
import { Route as DashboardCheckinIndexRouteImport } from './routes/dashboard/checkin/index'
import { Route as DashboardContentIndexRouteImport } from './routes/dashboard/content/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardFinanceIndexRouteImport } from './routes/dashboard/finance/index'
import { Route as DashboardFinanceVerificationRouteImport } from './routes/dashboard/finance/verification'
import { Route as DashboardIdCardIndexRouteImport } from './routes/dashboard/id-card/index'
import { Route as DashboardKtaIndexRouteImport } from './routes/dashboard/kta/index'
import { Route as DashboardMembersIndexRouteImport } from './routes/dashboard/members/index'
import { Route as DashboardNewsIndexRouteImport } from './routes/dashboard/news/index'
import { Route as DashboardOperationsIndexRouteImport } from './routes/dashboard/operations/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardTicketsIndexRouteImport } from './routes/dashboard/tickets/index'
import { Route as DashboardTicketsUuidRouteImport } from './routes/dashboard/tickets/$uuid'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as PortalOrdersIndexRouteImport } from './routes/portal/orders/index'
import { Route as PortalOrdersUuidRouteImport } from './routes/portal/orders/$uuid'
import { Route as DashboardFinanceTicketsIndexRouteImport } from './routes/dashboard/finance/tickets/index'
import { Route as DashboardOperationsEventsIdAttendanceRouteImport } from './routes/dashboard/operations/events.$id.attendance'
import { Route as DashboardOperationsEventsIdAttendeesRouteImport } from './routes/dashboard/operations/events.$id.attendees'
import { Route as DashboardOperationsEventsIdGatesRouteImport } from './routes/dashboard/operations/events.$id.gates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CekKtaRoute = CekKtaRouteImport.update({
  id: '/cek-kta',
  path: '/cek-kta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalBeritaRoute = PortalBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalEventRoute = PortalEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalIdCardRoute = PortalIdCardRouteImport.update({
  id: '/id-card',
  path: '/id-card',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProfilRoute = PortalProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalUbahPasswordRoute = PortalUbahPasswordRouteImport.update({
  id: '/ubah-password',
  path: '/ubah-password',
  getParentRoute: () => PortalRouteRoute,
} as any)
const DashboardActivityIndexRoute = DashboardActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAttendanceIndexRoute =
  DashboardAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAuditTimelineIndexRoute =
  DashboardAuditTimelineIndexRouteImport.update({
    id: '/audit-timeline/',
    path: '/audit-timeline/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCheckinIndexRoute = DashboardCheckinIndexRouteImport.update({
  id: '/checkin/',
  path: '/checkin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContentIndexRoute = DashboardContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceIndexRoute = DashboardFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceVerificationRoute =
  DashboardFinanceVerificationRouteImport.update({
    id: '/finance/verification',
    path: '/finance/verification',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardIdCardIndexRoute = DashboardIdCardIndexRouteImport.update({
  id: '/id-card/',
  path: '/id-card/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKtaIndexRoute = DashboardKtaIndexRouteImport.update({
  id: '/kta/',
  path: '/kta/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersIndexRoute = DashboardMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNewsIndexRoute = DashboardNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOperationsIndexRoute =
  DashboardOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsUuidRoute = DashboardTicketsUuidRouteImport.update({
  id: '/tickets/$uuid',
  path: '/tickets/$uuid',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const PortalOrdersIndexRoute = PortalOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOrdersUuidRoute = PortalOrdersUuidRouteImport.update({
  id: '/orders/$uuid',
  path: '/orders/$uuid',
  getParentRoute: () => PortalRouteRoute,
} as any)
const DashboardFinanceTicketsIndexRoute =
  DashboardFinanceTicketsIndexRouteImport.update({
    id: '/finance/tickets/',
    path: '/finance/tickets/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOperationsEventsIdAttendanceRoute =
  DashboardOperationsEventsIdAttendanceRouteImport.update({
    id: '/operations/events/$id/attendance',
    path: '/operations/events/$id/attendance',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOperationsEventsIdAttendeesRoute =
  DashboardOperationsEventsIdAttendeesRouteImport.update({
    id: '/operations/events/$id/attendees',
    path: '/operations/events/$id/attendees',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOperationsEventsIdGatesRoute =
  DashboardOperationsEventsIdGatesRouteImport.update({
    id: '/operations/events/$id/gates',
    path: '/operations/events/$id/gates',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cek-kta': typeof CekKtaRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/portal/berita': typeof PortalBeritaRoute
  '/portal/event': typeof PortalEventRoute
  '/portal/id-card': typeof PortalIdCardRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/ubah-password': typeof PortalUbahPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/finance/verification': typeof DashboardFinanceVerificationRoute
  '/dashboard/tickets/$uuid': typeof DashboardTicketsUuidRoute
  '/portal/orders/$uuid': typeof PortalOrdersUuidRoute
  '/dashboard/activity/': typeof DashboardActivityIndexRoute
  '/dashboard/attendance/': typeof DashboardAttendanceIndexRoute
  '/dashboard/audit-timeline/': typeof DashboardAuditTimelineIndexRoute
  '/dashboard/checkin/': typeof DashboardCheckinIndexRoute
  '/dashboard/content/': typeof DashboardContentIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/id-card/': typeof DashboardIdCardIndexRoute
  '/dashboard/kta/': typeof DashboardKtaIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/news/': typeof DashboardNewsIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/tickets/': typeof DashboardTicketsIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/portal/orders/': typeof PortalOrdersIndexRoute
  '/dashboard/finance/tickets/': typeof DashboardFinanceTicketsIndexRoute
  '/dashboard/operations/events/$id/attendance': typeof DashboardOperationsEventsIdAttendanceRoute
  '/dashboard/operations/events/$id/attendees': typeof DashboardOperationsEventsIdAttendeesRoute
  '/dashboard/operations/events/$id/gates': typeof DashboardOperationsEventsIdGatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cek-kta': typeof CekKtaRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/portal/berita': typeof PortalBeritaRoute
  '/portal/event': typeof PortalEventRoute
  '/portal/id-card': typeof PortalIdCardRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/ubah-password': typeof PortalUbahPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/dashboard/finance/verification': typeof DashboardFinanceVerificationRoute
  '/dashboard/tickets/$uuid': typeof DashboardTicketsUuidRoute
  '/portal/orders/$uuid': typeof PortalOrdersUuidRoute
  '/dashboard/activity': typeof DashboardActivityIndexRoute
  '/dashboard/attendance': typeof DashboardAttendanceIndexRoute
  '/dashboard/audit-timeline': typeof DashboardAuditTimelineIndexRoute
  '/dashboard/checkin': typeof DashboardCheckinIndexRoute
  '/dashboard/content': typeof DashboardContentIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/finance': typeof DashboardFinanceIndexRoute
  '/dashboard/id-card': typeof DashboardIdCardIndexRoute
  '/dashboard/kta': typeof DashboardKtaIndexRoute
  '/dashboard/members': typeof DashboardMembersIndexRoute
  '/dashboard/news': typeof DashboardNewsIndexRoute
  '/dashboard/operations': typeof DashboardOperationsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/tickets': typeof DashboardTicketsIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/portal/orders': typeof PortalOrdersIndexRoute
  '/dashboard/finance/tickets': typeof DashboardFinanceTicketsIndexRoute
  '/dashboard/operations/events/$id/attendance': typeof DashboardOperationsEventsIdAttendanceRoute
  '/dashboard/operations/events/$id/attendees': typeof DashboardOperationsEventsIdAttendeesRoute
  '/dashboard/operations/events/$id/gates': typeof DashboardOperationsEventsIdGatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cek-kta': typeof CekKtaRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/portal/berita': typeof PortalBeritaRoute
  '/portal/event': typeof PortalEventRoute
  '/portal/id-card': typeof PortalIdCardRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/ubah-password': typeof PortalUbahPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/finance/verification': typeof DashboardFinanceVerificationRoute
  '/dashboard/tickets/$uuid': typeof DashboardTicketsUuidRoute
  '/portal/orders/$uuid': typeof PortalOrdersUuidRoute
  '/dashboard/activity/': typeof DashboardActivityIndexRoute
  '/dashboard/attendance/': typeof DashboardAttendanceIndexRoute
  '/dashboard/audit-timeline/': typeof DashboardAuditTimelineIndexRoute
  '/dashboard/checkin/': typeof DashboardCheckinIndexRoute
  '/dashboard/content/': typeof DashboardContentIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/id-card/': typeof DashboardIdCardIndexRoute
  '/dashboard/kta/': typeof DashboardKtaIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/news/': typeof DashboardNewsIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/tickets/': typeof DashboardTicketsIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/portal/orders/': typeof PortalOrdersIndexRoute
  '/dashboard/finance/tickets/': typeof DashboardFinanceTicketsIndexRoute
  '/dashboard/operations/events/$id/attendance': typeof DashboardOperationsEventsIdAttendanceRoute
  '/dashboard/operations/events/$id/attendees': typeof DashboardOperationsEventsIdAttendeesRoute
  '/dashboard/operations/events/$id/gates': typeof DashboardOperationsEventsIdGatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/cek-kta'
    | '/contact'
    | '/forbidden'
    | '/gallery'
    | '/login'
    | '/news'
    | '/programs'
    | '/events/$id'
    | '/news/$id'
    | '/portal/berita'
    | '/portal/event'
    | '/portal/id-card'
    | '/portal/profil'
    | '/portal/ubah-password'
    | '/dashboard/'
    | '/events/'
    | '/portal/'
    | '/dashboard/finance/verification'
    | '/dashboard/tickets/$uuid'
    | '/portal/orders/$uuid'
    | '/dashboard/activity/'
    | '/dashboard/attendance/'
    | '/dashboard/audit-timeline/'
    | '/dashboard/checkin/'
    | '/dashboard/content/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/id-card/'
    | '/dashboard/kta/'
    | '/dashboard/members/'
    | '/dashboard/news/'
    | '/dashboard/operations/'
    | '/dashboard/profile/'
    | '/dashboard/tickets/'
    | '/dashboard/transactions/'
    | '/portal/orders/'
    | '/dashboard/finance/tickets/'
    | '/dashboard/operations/events/$id/attendance'
    | '/dashboard/operations/events/$id/attendees'
    | '/dashboard/operations/events/$id/gates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cek-kta'
    | '/contact'
    | '/forbidden'
    | '/gallery'
    | '/login'
    | '/news'
    | '/programs'
    | '/events/$id'
    | '/news/$id'
    | '/portal/berita'
    | '/portal/event'
    | '/portal/id-card'
    | '/portal/profil'
    | '/portal/ubah-password'
    | '/dashboard'
    | '/events'
    | '/portal'
    | '/dashboard/finance/verification'
    | '/dashboard/tickets/$uuid'
    | '/portal/orders/$uuid'
    | '/dashboard/activity'
    | '/dashboard/attendance'
    | '/dashboard/audit-timeline'
    | '/dashboard/checkin'
    | '/dashboard/content'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/id-card'
    | '/dashboard/kta'
    | '/dashboard/members'
    | '/dashboard/news'
    | '/dashboard/operations'
    | '/dashboard/profile'
    | '/dashboard/tickets'
    | '/dashboard/transactions'
    | '/portal/orders'
    | '/dashboard/finance/tickets'
    | '/dashboard/operations/events/$id/attendance'
    | '/dashboard/operations/events/$id/attendees'
    | '/dashboard/operations/events/$id/gates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/cek-kta'
    | '/contact'
    | '/forbidden'
    | '/gallery'
    | '/login'
    | '/news'
    | '/programs'
    | '/events/$id'
    | '/news/$id'
    | '/portal/berita'
    | '/portal/event'
    | '/portal/id-card'
    | '/portal/profil'
    | '/portal/ubah-password'
    | '/dashboard/'
    | '/events/'
    | '/portal/'
    | '/dashboard/finance/verification'
    | '/dashboard/tickets/$uuid'
    | '/portal/orders/$uuid'
    | '/dashboard/activity/'
    | '/dashboard/attendance/'
    | '/dashboard/audit-timeline/'
    | '/dashboard/checkin/'
    | '/dashboard/content/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/id-card/'
    | '/dashboard/kta/'
    | '/dashboard/members/'
    | '/dashboard/news/'
    | '/dashboard/operations/'
    | '/dashboard/profile/'
    | '/dashboard/tickets/'
    | '/dashboard/transactions/'
    | '/portal/orders/'
    | '/dashboard/finance/tickets/'
    | '/dashboard/operations/events/$id/attendance'
    | '/dashboard/operations/events/$id/attendees'
    | '/dashboard/operations/events/$id/gates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CekKtaRoute: typeof CekKtaRoute
  ContactRoute: typeof ContactRoute
  ForbiddenRoute: typeof ForbiddenRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-kta': {
      id: '/cek-kta'
      path: '/cek-kta'
      fullPath: '/cek-kta'
      preLoaderRoute: typeof CekKtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/berita': {
      id: '/portal/berita'
      path: '/berita'
      fullPath: '/portal/berita'
      preLoaderRoute: typeof PortalBeritaRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/event': {
      id: '/portal/event'
      path: '/event'
      fullPath: '/portal/event'
      preLoaderRoute: typeof PortalEventRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/id-card': {
      id: '/portal/id-card'
      path: '/id-card'
      fullPath: '/portal/id-card'
      preLoaderRoute: typeof PortalIdCardRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profil': {
      id: '/portal/profil'
      path: '/profil'
      fullPath: '/portal/profil'
      preLoaderRoute: typeof PortalProfilRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/ubah-password': {
      id: '/portal/ubah-password'
      path: '/ubah-password'
      fullPath: '/portal/ubah-password'
      preLoaderRoute: typeof PortalUbahPasswordRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/dashboard/activity/': {
      id: '/dashboard/activity/'
      path: '/activity'
      fullPath: '/dashboard/activity/'
      preLoaderRoute: typeof DashboardActivityIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/attendance/': {
      id: '/dashboard/attendance/'
      path: '/attendance'
      fullPath: '/dashboard/attendance/'
      preLoaderRoute: typeof DashboardAttendanceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audit-timeline/': {
      id: '/dashboard/audit-timeline/'
      path: '/audit-timeline'
      fullPath: '/dashboard/audit-timeline/'
      preLoaderRoute: typeof DashboardAuditTimelineIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/checkin/': {
      id: '/dashboard/checkin/'
      path: '/checkin'
      fullPath: '/dashboard/checkin/'
      preLoaderRoute: typeof DashboardCheckinIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/content/': {
      id: '/dashboard/content/'
      path: '/content'
      fullPath: '/dashboard/content/'
      preLoaderRoute: typeof DashboardContentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance/': {
      id: '/dashboard/finance/'
      path: '/finance'
      fullPath: '/dashboard/finance/'
      preLoaderRoute: typeof DashboardFinanceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance/verification': {
      id: '/dashboard/finance/verification'
      path: '/finance/verification'
      fullPath: '/dashboard/finance/verification'
      preLoaderRoute: typeof DashboardFinanceVerificationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/id-card/': {
      id: '/dashboard/id-card/'
      path: '/id-card'
      fullPath: '/dashboard/id-card/'
      preLoaderRoute: typeof DashboardIdCardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/kta/': {
      id: '/dashboard/kta/'
      path: '/kta'
      fullPath: '/dashboard/kta/'
      preLoaderRoute: typeof DashboardKtaIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/': {
      id: '/dashboard/members/'
      path: '/members'
      fullPath: '/dashboard/members/'
      preLoaderRoute: typeof DashboardMembersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/news/': {
      id: '/dashboard/news/'
      path: '/news'
      fullPath: '/dashboard/news/'
      preLoaderRoute: typeof DashboardNewsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/operations/': {
      id: '/dashboard/operations/'
      path: '/operations'
      fullPath: '/dashboard/operations/'
      preLoaderRoute: typeof DashboardOperationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tickets/': {
      id: '/dashboard/tickets/'
      path: '/tickets'
      fullPath: '/dashboard/tickets/'
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tickets/$uuid': {
      id: '/dashboard/tickets/$uuid'
      path: '/tickets/$uuid'
      fullPath: '/dashboard/tickets/$uuid'
      preLoaderRoute: typeof DashboardTicketsUuidRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/transactions'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/portal/orders/': {
      id: '/portal/orders/'
      path: '/orders'
      fullPath: '/portal/orders/'
      preLoaderRoute: typeof PortalOrdersIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/orders/$uuid': {
      id: '/portal/orders/$uuid'
      path: '/orders/$uuid'
      fullPath: '/portal/orders/$uuid'
      preLoaderRoute: typeof PortalOrdersUuidRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/dashboard/finance/tickets/': {
      id: '/dashboard/finance/tickets/'
      path: '/finance/tickets'
      fullPath: '/dashboard/finance/tickets/'
      preLoaderRoute: typeof DashboardFinanceTicketsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/operations/events/$id/attendance': {
      id: '/dashboard/operations/events/$id/attendance'
      path: '/operations/events/$id/attendance'
      fullPath: '/dashboard/operations/events/$id/attendance'
      preLoaderRoute: typeof DashboardOperationsEventsIdAttendanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/operations/events/$id/attendees': {
      id: '/dashboard/operations/events/$id/attendees'
      path: '/operations/events/$id/attendees'
      fullPath: '/dashboard/operations/events/$id/attendees'
      preLoaderRoute: typeof DashboardOperationsEventsIdAttendeesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/operations/events/$id/gates': {
      id: '/dashboard/operations/events/$id/gates'
      path: '/operations/events/$id/gates'
      fullPath: '/dashboard/operations/events/$id/gates'
      preLoaderRoute: typeof DashboardOperationsEventsIdGatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFinanceVerificationRoute: typeof DashboardFinanceVerificationRoute
  DashboardTicketsUuidRoute: typeof DashboardTicketsUuidRoute
  DashboardActivityIndexRoute: typeof DashboardActivityIndexRoute
  DashboardAttendanceIndexRoute: typeof DashboardAttendanceIndexRoute
  DashboardAuditTimelineIndexRoute: typeof DashboardAuditTimelineIndexRoute
  DashboardCheckinIndexRoute: typeof DashboardCheckinIndexRoute
  DashboardContentIndexRoute: typeof DashboardContentIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardFinanceIndexRoute: typeof DashboardFinanceIndexRoute
  DashboardIdCardIndexRoute: typeof DashboardIdCardIndexRoute
  DashboardKtaIndexRoute: typeof DashboardKtaIndexRoute
  DashboardMembersIndexRoute: typeof DashboardMembersIndexRoute
  DashboardNewsIndexRoute: typeof DashboardNewsIndexRoute
  DashboardOperationsIndexRoute: typeof DashboardOperationsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardFinanceTicketsIndexRoute: typeof DashboardFinanceTicketsIndexRoute
  DashboardOperationsEventsIdAttendanceRoute: typeof DashboardOperationsEventsIdAttendanceRoute
  DashboardOperationsEventsIdAttendeesRoute: typeof DashboardOperationsEventsIdAttendeesRoute
  DashboardOperationsEventsIdGatesRoute: typeof DashboardOperationsEventsIdGatesRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFinanceVerificationRoute: DashboardFinanceVerificationRoute,
  DashboardTicketsUuidRoute: DashboardTicketsUuidRoute,
  DashboardActivityIndexRoute: DashboardActivityIndexRoute,
  DashboardAttendanceIndexRoute: DashboardAttendanceIndexRoute,
  DashboardAuditTimelineIndexRoute: DashboardAuditTimelineIndexRoute,
  DashboardCheckinIndexRoute: DashboardCheckinIndexRoute,
  DashboardContentIndexRoute: DashboardContentIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardFinanceIndexRoute: DashboardFinanceIndexRoute,
  DashboardIdCardIndexRoute: DashboardIdCardIndexRoute,
  DashboardKtaIndexRoute: DashboardKtaIndexRoute,
  DashboardMembersIndexRoute: DashboardMembersIndexRoute,
  DashboardNewsIndexRoute: DashboardNewsIndexRoute,
  DashboardOperationsIndexRoute: DashboardOperationsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardFinanceTicketsIndexRoute: DashboardFinanceTicketsIndexRoute,
  DashboardOperationsEventsIdAttendanceRoute:
    DashboardOperationsEventsIdAttendanceRoute,
  DashboardOperationsEventsIdAttendeesRoute:
    DashboardOperationsEventsIdAttendeesRoute,
  DashboardOperationsEventsIdGatesRoute: DashboardOperationsEventsIdGatesRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalBeritaRoute: typeof PortalBeritaRoute
  PortalEventRoute: typeof PortalEventRoute
  PortalIdCardRoute: typeof PortalIdCardRoute
  PortalProfilRoute: typeof PortalProfilRoute
  PortalUbahPasswordRoute: typeof PortalUbahPasswordRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalOrdersUuidRoute: typeof PortalOrdersUuidRoute
  PortalOrdersIndexRoute: typeof PortalOrdersIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalBeritaRoute: PortalBeritaRoute,
  PortalEventRoute: PortalEventRoute,
  PortalIdCardRoute: PortalIdCardRoute,
  PortalProfilRoute: PortalProfilRoute,
  PortalUbahPasswordRoute: PortalUbahPasswordRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalOrdersUuidRoute: PortalOrdersUuidRoute,
  PortalOrdersIndexRoute: PortalOrdersIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CekKtaRoute: CekKtaRoute,
  ContactRoute: ContactRoute,
  ForbiddenRoute: ForbiddenRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
