/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalBeritaRouteImport } from './routes/portal/berita'
import { Route as PortalEventRouteImport } from './routes/portal/event'
import { Route as PortalIdCardRouteImport } from './routes/portal/id-card'
import { Route as PortalOrdersRouteImport } from './routes/portal/orders'
import { Route as PortalProfilRouteImport } from './routes/portal/profil'
import { Route as PortalUbahPasswordRouteImport } from './routes/portal/ubah-password'
import { Route as DashboardActivityIndexRouteImport } from './routes/dashboard/activity/index'
import { Route as DashboardAttendanceIndexRouteImport } from './routes/dashboard/attendance/index'
import { Route as DashboardCheckinIndexRouteImport } from './routes/dashboard/checkin/index'
import { Route as DashboardContentIndexRouteImport } from './routes/dashboard/content/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardFinanceIndexRouteImport } from './routes/dashboard/finance/index'
import { Route as DashboardIdCardIndexRouteImport } from './routes/dashboard/id-card/index'
import { Route as DashboardMembersIndexRouteImport } from './routes/dashboard/members/index'
import { Route as DashboardNewsIndexRouteImport } from './routes/dashboard/news/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as PortalOrdersUuidRouteImport } from './routes/portal/orders.$uuid'
import { Route as DashboardFinanceTicketsIndexRouteImport } from './routes/dashboard/finance/tickets/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalBeritaRoute = PortalBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalEventRoute = PortalEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalIdCardRoute = PortalIdCardRouteImport.update({
  id: '/id-card',
  path: '/id-card',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProfilRoute = PortalProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalUbahPasswordRoute = PortalUbahPasswordRouteImport.update({
  id: '/ubah-password',
  path: '/ubah-password',
  getParentRoute: () => PortalRouteRoute,
} as any)
const DashboardActivityIndexRoute = DashboardActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAttendanceIndexRoute =
  DashboardAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCheckinIndexRoute = DashboardCheckinIndexRouteImport.update({
  id: '/checkin/',
  path: '/checkin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContentIndexRoute = DashboardContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceIndexRoute = DashboardFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIdCardIndexRoute = DashboardIdCardIndexRouteImport.update({
  id: '/id-card/',
  path: '/id-card/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersIndexRoute = DashboardMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNewsIndexRoute = DashboardNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const PortalOrdersUuidRoute = PortalOrdersUuidRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => PortalOrdersRoute,
} as any)
const DashboardFinanceTicketsIndexRoute =
  DashboardFinanceTicketsIndexRouteImport.update({
    id: '/finance/tickets/',
    path: '/finance/tickets/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/portal/berita': typeof PortalBeritaRoute
  '/portal/event': typeof PortalEventRoute
  '/portal/id-card': typeof PortalIdCardRoute
  '/portal/orders': typeof PortalOrdersRouteWithChildren
  '/portal/profil': typeof PortalProfilRoute
  '/portal/ubah-password': typeof PortalUbahPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/orders/$uuid': typeof PortalOrdersUuidRoute
  '/dashboard/activity/': typeof DashboardActivityIndexRoute
  '/dashboard/attendance/': typeof DashboardAttendanceIndexRoute
  '/dashboard/checkin/': typeof DashboardCheckinIndexRoute
  '/dashboard/content/': typeof DashboardContentIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/id-card/': typeof DashboardIdCardIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/news/': typeof DashboardNewsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/finance/tickets/': typeof DashboardFinanceTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/portal/berita': typeof PortalBeritaRoute
  '/portal/event': typeof PortalEventRoute
  '/portal/id-card': typeof PortalIdCardRoute
  '/portal/orders': typeof PortalOrdersRouteWithChildren
  '/portal/profil': typeof PortalProfilRoute
  '/portal/ubah-password': typeof PortalUbahPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/orders/$uuid': typeof PortalOrdersUuidRoute
  '/dashboard/activity': typeof DashboardActivityIndexRoute
  '/dashboard/attendance': typeof DashboardAttendanceIndexRoute
  '/dashboard/checkin': typeof DashboardCheckinIndexRoute
  '/dashboard/content': typeof DashboardContentIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/finance': typeof DashboardFinanceIndexRoute
  '/dashboard/id-card': typeof DashboardIdCardIndexRoute
  '/dashboard/members': typeof DashboardMembersIndexRoute
  '/dashboard/news': typeof DashboardNewsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/finance/tickets': typeof DashboardFinanceTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/portal/berita': typeof PortalBeritaRoute
  '/portal/event': typeof PortalEventRoute
  '/portal/id-card': typeof PortalIdCardRoute
  '/portal/orders': typeof PortalOrdersRouteWithChildren
  '/portal/profil': typeof PortalProfilRoute
  '/portal/ubah-password': typeof PortalUbahPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/orders/$uuid': typeof PortalOrdersUuidRoute
  '/dashboard/activity/': typeof DashboardActivityIndexRoute
  '/dashboard/attendance/': typeof DashboardAttendanceIndexRoute
  '/dashboard/checkin/': typeof DashboardCheckinIndexRoute
  '/dashboard/content/': typeof DashboardContentIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/id-card/': typeof DashboardIdCardIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/news/': typeof DashboardNewsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/finance/tickets/': typeof DashboardFinanceTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/news'
    | '/programs'
    | '/events/$id'
    | '/news/$id'
    | '/portal/berita'
    | '/portal/event'
    | '/portal/id-card'
    | '/portal/orders'
    | '/portal/profil'
    | '/portal/ubah-password'
    | '/dashboard/'
    | '/portal/'
    | '/portal/orders/$uuid'
    | '/dashboard/activity/'
    | '/dashboard/attendance/'
    | '/dashboard/checkin/'
    | '/dashboard/content/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/id-card/'
    | '/dashboard/members/'
    | '/dashboard/news/'
    | '/dashboard/profile/'
    | '/dashboard/transactions/'
    | '/dashboard/finance/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/news'
    | '/programs'
    | '/events/$id'
    | '/news/$id'
    | '/portal/berita'
    | '/portal/event'
    | '/portal/id-card'
    | '/portal/orders'
    | '/portal/profil'
    | '/portal/ubah-password'
    | '/dashboard'
    | '/portal'
    | '/portal/orders/$uuid'
    | '/dashboard/activity'
    | '/dashboard/attendance'
    | '/dashboard/checkin'
    | '/dashboard/content'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/id-card'
    | '/dashboard/members'
    | '/dashboard/news'
    | '/dashboard/profile'
    | '/dashboard/transactions'
    | '/dashboard/finance/tickets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/news'
    | '/programs'
    | '/events/$id'
    | '/news/$id'
    | '/portal/berita'
    | '/portal/event'
    | '/portal/id-card'
    | '/portal/orders'
    | '/portal/profil'
    | '/portal/ubah-password'
    | '/dashboard/'
    | '/portal/'
    | '/portal/orders/$uuid'
    | '/dashboard/activity/'
    | '/dashboard/attendance/'
    | '/dashboard/checkin/'
    | '/dashboard/content/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/id-card/'
    | '/dashboard/members/'
    | '/dashboard/news/'
    | '/dashboard/profile/'
    | '/dashboard/transactions/'
    | '/dashboard/finance/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/berita': {
      id: '/portal/berita'
      path: '/berita'
      fullPath: '/portal/berita'
      preLoaderRoute: typeof PortalBeritaRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/event': {
      id: '/portal/event'
      path: '/event'
      fullPath: '/portal/event'
      preLoaderRoute: typeof PortalEventRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/id-card': {
      id: '/portal/id-card'
      path: '/id-card'
      fullPath: '/portal/id-card'
      preLoaderRoute: typeof PortalIdCardRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profil': {
      id: '/portal/profil'
      path: '/profil'
      fullPath: '/portal/profil'
      preLoaderRoute: typeof PortalProfilRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/ubah-password': {
      id: '/portal/ubah-password'
      path: '/ubah-password'
      fullPath: '/portal/ubah-password'
      preLoaderRoute: typeof PortalUbahPasswordRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/dashboard/activity/': {
      id: '/dashboard/activity/'
      path: '/activity'
      fullPath: '/dashboard/activity/'
      preLoaderRoute: typeof DashboardActivityIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/attendance/': {
      id: '/dashboard/attendance/'
      path: '/attendance'
      fullPath: '/dashboard/attendance/'
      preLoaderRoute: typeof DashboardAttendanceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/checkin/': {
      id: '/dashboard/checkin/'
      path: '/checkin'
      fullPath: '/dashboard/checkin/'
      preLoaderRoute: typeof DashboardCheckinIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/content/': {
      id: '/dashboard/content/'
      path: '/content'
      fullPath: '/dashboard/content/'
      preLoaderRoute: typeof DashboardContentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance/': {
      id: '/dashboard/finance/'
      path: '/finance'
      fullPath: '/dashboard/finance/'
      preLoaderRoute: typeof DashboardFinanceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/id-card/': {
      id: '/dashboard/id-card/'
      path: '/id-card'
      fullPath: '/dashboard/id-card/'
      preLoaderRoute: typeof DashboardIdCardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/': {
      id: '/dashboard/members/'
      path: '/members'
      fullPath: '/dashboard/members/'
      preLoaderRoute: typeof DashboardMembersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/news/': {
      id: '/dashboard/news/'
      path: '/news'
      fullPath: '/dashboard/news/'
      preLoaderRoute: typeof DashboardNewsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/transactions'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/portal/orders/$uuid': {
      id: '/portal/orders/$uuid'
      path: '/$uuid'
      fullPath: '/portal/orders/$uuid'
      preLoaderRoute: typeof PortalOrdersUuidRouteImport
      parentRoute: typeof PortalOrdersRoute
    }
    '/dashboard/finance/tickets/': {
      id: '/dashboard/finance/tickets/'
      path: '/finance/tickets'
      fullPath: '/dashboard/finance/tickets/'
      preLoaderRoute: typeof DashboardFinanceTicketsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardActivityIndexRoute: typeof DashboardActivityIndexRoute
  DashboardAttendanceIndexRoute: typeof DashboardAttendanceIndexRoute
  DashboardCheckinIndexRoute: typeof DashboardCheckinIndexRoute
  DashboardContentIndexRoute: typeof DashboardContentIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardFinanceIndexRoute: typeof DashboardFinanceIndexRoute
  DashboardIdCardIndexRoute: typeof DashboardIdCardIndexRoute
  DashboardMembersIndexRoute: typeof DashboardMembersIndexRoute
  DashboardNewsIndexRoute: typeof DashboardNewsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardFinanceTicketsIndexRoute: typeof DashboardFinanceTicketsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardActivityIndexRoute: DashboardActivityIndexRoute,
  DashboardAttendanceIndexRoute: DashboardAttendanceIndexRoute,
  DashboardCheckinIndexRoute: DashboardCheckinIndexRoute,
  DashboardContentIndexRoute: DashboardContentIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardFinanceIndexRoute: DashboardFinanceIndexRoute,
  DashboardIdCardIndexRoute: DashboardIdCardIndexRoute,
  DashboardMembersIndexRoute: DashboardMembersIndexRoute,
  DashboardNewsIndexRoute: DashboardNewsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardFinanceTicketsIndexRoute: DashboardFinanceTicketsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PortalOrdersRouteChildren {
  PortalOrdersUuidRoute: typeof PortalOrdersUuidRoute
}

const PortalOrdersRouteChildren: PortalOrdersRouteChildren = {
  PortalOrdersUuidRoute: PortalOrdersUuidRoute,
}

const PortalOrdersRouteWithChildren = PortalOrdersRoute._addFileChildren(
  PortalOrdersRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalBeritaRoute: typeof PortalBeritaRoute
  PortalEventRoute: typeof PortalEventRoute
  PortalIdCardRoute: typeof PortalIdCardRoute
  PortalOrdersRoute: typeof PortalOrdersRouteWithChildren
  PortalProfilRoute: typeof PortalProfilRoute
  PortalUbahPasswordRoute: typeof PortalUbahPasswordRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalBeritaRoute: PortalBeritaRoute,
  PortalEventRoute: PortalEventRoute,
  PortalIdCardRoute: PortalIdCardRoute,
  PortalOrdersRoute: PortalOrdersRouteWithChildren,
  PortalProfilRoute: PortalProfilRoute,
  PortalUbahPasswordRoute: PortalUbahPasswordRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
